[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npm run build"]

[start]
# Mude para este comando que mantém o Nginx rodando:
cmd = "nginx -g 'daemon off;'"
